sonar.projectKey=badoriie_rich-statusline
sonar.organization=badoriie
sonar.projectName=rich-statusline
sonar.projectVersion=1.0.3

sonar.sources=scripts,.githooks
sonar.exclusions=**/.git/**,**/.idea/**,**/.claude/**
